export enum NavigationIconType {
  Home = 'Home',
  BotViewer = 'Bot Viewer',
  DataSource = 'Data Source',
  Account = 'Account',
  Calendar = 'Calendar',
  Meet = 'Meet',
  Activities = 'Activities',
  Publish = 'Publish',
  Saved = 'Saved',
  Settings = 'Settings',
  Contact = 'Contact',
  Profile = 'Profile',
  Compose = 'Compose',
  Inbox = 'Inbox',
  Send = 'Send',
  Draft = 'Draft',
  Configure = 'Configure',
  EmbedSettings = 'EmbedSettings',
  Favourite = 'Favourite',
  BrandSetup = 'Brand Setup',
  CreatePoster= 'Create Poster',
  BotStore = 'Bot Store', // New icon
  Payment = 'Payment',   // New icon
}
